// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type GrupoReflexivoDocumentDataSlicesSlice = CtaSlice;

type GrupoReflexivoDocumentDataSlices1Slice = CtaSlice;

/**
 * Content for grupo-reflexivo documents
 */
interface GrupoReflexivoDocumentData {
  /**
   * Slice Zone field in *grupo-reflexivo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_reflexivo.slices[]
   * - **Tab**: Desktop
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GrupoReflexivoDocumentDataSlicesSlice> /**
   * Slice Zone field in *grupo-reflexivo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_reflexivo.slices1[]
   * - **Tab**: Mobile
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<GrupoReflexivoDocumentDataSlices1Slice>;
}

/**
 * grupo-reflexivo document from Prismic
 *
 * - **API ID**: `grupo_reflexivo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GrupoReflexivoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GrupoReflexivoDocumentData>,
    "grupo_reflexivo",
    Lang
  >;

export type AllDocumentTypes = GrupoReflexivoDocument;

/**
 * Primary content in *Cta → Desktop → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Imagem field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Desktop variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cta → Mobile → Primary*
 */
export interface CtaSliceMobilePrimary {
  /**
   * Imagem field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Mobile variation for Cta Slice
 *
 * - **API ID**: `mobile`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceMobile = prismic.SharedSliceVariation<
  "mobile",
  Simplify<CtaSliceMobilePrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault | CtaSliceMobile;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GrupoReflexivoDocument,
      GrupoReflexivoDocumentData,
      GrupoReflexivoDocumentDataSlicesSlice,
      GrupoReflexivoDocumentDataSlices1Slice,
      AllDocumentTypes,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceMobilePrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceMobile,
    };
  }
}
