// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type EstudoDeCuidadoDocumentDataSlicesSlice =
  | WhoWeAreSlice
  | PodcastSlice
  | FormBlockSlice
  | TextBlockSlice
  | SecondaryCtaSlice;

/**
 * Content for Estudo de Cuidado documents
 */
interface EstudoDeCuidadoDocumentData {
  /**
   * Slice Zone field in *Estudo de Cuidado*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: estudo_de_cuidado.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EstudoDeCuidadoDocumentDataSlicesSlice>;
}

/**
 * Estudo de Cuidado document from Prismic
 *
 * - **API ID**: `estudo_de_cuidado`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EstudoDeCuidadoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EstudoDeCuidadoDocumentData>,
    "estudo_de_cuidado",
    Lang
  >;

type GrupoReflexivoDocumentDataSlicesSlice =
  | DownloadSlice
  | StepsSlice
  | FaqSlice
  | StatementSlice
  | AboutSlice
  | CtaSlice;

type GrupoReflexivoDocumentDataSlices1Slice =
  | DownloadSlice
  | StepsSlice
  | FaqSlice
  | StatementSlice
  | AboutSlice
  | CtaSlice;

/**
 * Content for Grupo Reflexivo documents
 */
interface GrupoReflexivoDocumentData {
  /**
   * Slice Zone field in *Grupo Reflexivo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_reflexivo.slices[]
   * - **Tab**: Desktop
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GrupoReflexivoDocumentDataSlicesSlice> /**
   * Slice Zone field in *Grupo Reflexivo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_reflexivo.slices1[]
   * - **Tab**: Mobile
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<GrupoReflexivoDocumentDataSlices1Slice>;
}

/**
 * Grupo Reflexivo document from Prismic
 *
 * - **API ID**: `grupo_reflexivo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GrupoReflexivoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GrupoReflexivoDocumentData>,
    "grupo_reflexivo",
    Lang
  >;

export type AllDocumentTypes = EstudoDeCuidadoDocument | GrupoReflexivoDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Título field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Cta → Desktop → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Imagem field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Desktop variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cta → Mobile → Primary*
 */
export interface CtaSliceMobilePrimary {
  /**
   * Imagem field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Mobile variation for Cta Slice
 *
 * - **API ID**: `mobile`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceMobile = prismic.SharedSliceVariation<
  "mobile",
  Simplify<CtaSliceMobilePrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault | CtaSliceMobile;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *Download → Default → Primary*
 */
export interface DownloadSliceDefaultPrimary {
  /**
   * Título field in *Download → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Download → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Download Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DownloadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DownloadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Download*
 */
type DownloadSliceVariation = DownloadSliceDefault;

/**
 * Download Shared Slice
 *
 * - **API ID**: `download`
 * - **Description**: Download
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DownloadSlice = prismic.SharedSlice<
  "download",
  DownloadSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → Questões*
 */
export interface FaqSliceDefaultPrimaryQuestionsItem {
  /**
   * Pergunta field in *Faq → Default → Primary → Questões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Resposta field in *Faq → Default → Primary → Questões*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Questões field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryQuestionsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Default variation for FormBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FormBlock*
 */
type FormBlockSliceVariation = FormBlockSliceDefault;

/**
 * FormBlock Shared Slice
 *
 * - **API ID**: `form_block`
 * - **Description**: FormBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormBlockSlice = prismic.SharedSlice<
  "form_block",
  FormBlockSliceVariation
>;

/**
 * Default variation for Podcast Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PodcastSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Podcast*
 */
type PodcastSliceVariation = PodcastSliceDefault;

/**
 * Podcast Shared Slice
 *
 * - **API ID**: `podcast`
 * - **Description**: Podcast
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PodcastSlice = prismic.SharedSlice<
  "podcast",
  PodcastSliceVariation
>;

/**
 * Primary content in *SecondaryCta → Default → Primary*
 */
export interface SecondaryCtaSliceDefaultPrimary {
  /**
   * Título field in *SecondaryCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *SecondaryCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_cta.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Imagem Principal field in *SecondaryCta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_cta.default.primary.primaryImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  primaryImage: prismic.ImageField<never>;

  /**
   * Imagem Secundária field in *SecondaryCta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_cta.default.primary.secondaryImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  secondaryImage: prismic.ImageField<never>;
}

/**
 * Default variation for SecondaryCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondaryCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecondaryCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecondaryCta*
 */
type SecondaryCtaSliceVariation = SecondaryCtaSliceDefault;

/**
 * SecondaryCta Shared Slice
 *
 * - **API ID**: `secondary_cta`
 * - **Description**: SecondaryCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondaryCtaSlice = prismic.SharedSlice<
  "secondary_cta",
  SecondaryCtaSliceVariation
>;

/**
 * Item in *Statements → Default → Primary → Depoimentos*
 */
export interface StatementSliceDefaultPrimaryStatementsItem {
  /**
   * Nome field in *Statements → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Detalhes field in *Statements → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[].details
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  details: prismic.KeyTextField;

  /**
   * Depoimento field in *Statements → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[].statement
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statement: prismic.KeyTextField;

  /**
   * Imagem field in *Statements → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Statements → Default → Primary*
 */
export interface StatementSliceDefaultPrimary {
  /**
   * Depoimentos field in *Statements → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  statements: prismic.GroupField<
    Simplify<StatementSliceDefaultPrimaryStatementsItem>
  >;
}

/**
 * Default variation for Statements Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatementSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Statements*
 */
type StatementSliceVariation = StatementSliceDefault;

/**
 * Statements Shared Slice
 *
 * - **API ID**: `statement`
 * - **Description**: Statement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementSlice = prismic.SharedSlice<
  "statement",
  StatementSliceVariation
>;

/**
 * Primary content in *Inscricoes → Default → Primary*
 */
export interface StepsSliceDefaultPrimary {
  /**
   * Título field in *Inscricoes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtítulo field in *Inscricoes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Texto field in *Inscricoes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Inscricoes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Inscricoes*
 */
type StepsSliceVariation = StepsSliceDefault;

/**
 * Inscricoes Shared Slice
 *
 * - **API ID**: `steps`
 * - **Description**: Steps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSlice = prismic.SharedSlice<"steps", StepsSliceVariation>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Default variation for WhoWeAre Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhoWeAreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *WhoWeAre*
 */
type WhoWeAreSliceVariation = WhoWeAreSliceDefault;

/**
 * WhoWeAre Shared Slice
 *
 * - **API ID**: `who_we_are`
 * - **Description**: WhoWeAre
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhoWeAreSlice = prismic.SharedSlice<
  "who_we_are",
  WhoWeAreSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EstudoDeCuidadoDocument,
      EstudoDeCuidadoDocumentData,
      EstudoDeCuidadoDocumentDataSlicesSlice,
      GrupoReflexivoDocument,
      GrupoReflexivoDocumentData,
      GrupoReflexivoDocumentDataSlicesSlice,
      GrupoReflexivoDocumentDataSlices1Slice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceMobilePrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceMobile,
      DownloadSlice,
      DownloadSliceDefaultPrimary,
      DownloadSliceVariation,
      DownloadSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryQuestionsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      FormBlockSlice,
      FormBlockSliceVariation,
      FormBlockSliceDefault,
      PodcastSlice,
      PodcastSliceVariation,
      PodcastSliceDefault,
      SecondaryCtaSlice,
      SecondaryCtaSliceDefaultPrimary,
      SecondaryCtaSliceVariation,
      SecondaryCtaSliceDefault,
      StatementSlice,
      StatementSliceDefaultPrimaryStatementsItem,
      StatementSliceDefaultPrimary,
      StatementSliceVariation,
      StatementSliceDefault,
      StepsSlice,
      StepsSliceDefaultPrimary,
      StepsSliceVariation,
      StepsSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      WhoWeAreSlice,
      WhoWeAreSliceVariation,
      WhoWeAreSliceDefault,
    };
  }
}
