// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type GrupoReflexivoDocumentDataSlicesSlice =
  | StepsSlice
  | FaqSlice
  | StatementSlice
  | AboutSlice
  | CtaSlice;

type GrupoReflexivoDocumentDataSlices1Slice =
  | StepsSlice
  | FaqSlice
  | StatementSlice
  | AboutSlice
  | CtaSlice;

/**
 * Content for grupo-reflexivo documents
 */
interface GrupoReflexivoDocumentData {
  /**
   * Slice Zone field in *grupo-reflexivo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_reflexivo.slices[]
   * - **Tab**: Desktop
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GrupoReflexivoDocumentDataSlicesSlice> /**
   * Slice Zone field in *grupo-reflexivo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: grupo_reflexivo.slices1[]
   * - **Tab**: Mobile
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<GrupoReflexivoDocumentDataSlices1Slice>;
}

/**
 * grupo-reflexivo document from Prismic
 *
 * - **API ID**: `grupo_reflexivo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GrupoReflexivoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GrupoReflexivoDocumentData>,
    "grupo_reflexivo",
    Lang
  >;

export type AllDocumentTypes = GrupoReflexivoDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Título field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Cta → Desktop → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Imagem field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Cta → Desktop → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Desktop variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cta → Mobile → Primary*
 */
export interface CtaSliceMobilePrimary {
  /**
   * Imagem field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Cta → Mobile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.mobile.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Mobile variation for Cta Slice
 *
 * - **API ID**: `mobile`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceMobile = prismic.SharedSliceVariation<
  "mobile",
  Simplify<CtaSliceMobilePrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault | CtaSliceMobile;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Faq → Default → Primary → Questões*
 */
export interface FaqSliceDefaultPrimaryQuestionsItem {
  /**
   * Pergunta field in *Faq → Default → Primary → Questões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Resposta field in *Faq → Default → Primary → Questões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Questões field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryQuestionsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Item in *Statements → Default → Primary → Depoimentos*
 */
export interface StatementSliceDefaultPrimaryStatementsItem {
  /**
   * Nome field in *Statements → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Detalhes field in *Statements → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[].details
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  details: prismic.KeyTextField;

  /**
   * Depoimento field in *Statements → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[].statement
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statement: prismic.KeyTextField;

  /**
   * Imagem field in *Statements → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Statements → Default → Primary*
 */
export interface StatementSliceDefaultPrimary {
  /**
   * Depoimentos field in *Statements → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.statements[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  statements: prismic.GroupField<
    Simplify<StatementSliceDefaultPrimaryStatementsItem>
  >;
}

/**
 * Default variation for Statements Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatementSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Statements*
 */
type StatementSliceVariation = StatementSliceDefault;

/**
 * Statements Shared Slice
 *
 * - **API ID**: `statement`
 * - **Description**: Statement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementSlice = prismic.SharedSlice<
  "statement",
  StatementSliceVariation
>;

/**
 * Item in *Steps → Default → Primary → Etapas*
 */
export interface StepsSliceDefaultPrimaryStepsItem {
  /**
   * Título field in *Steps → Default → Primary → Etapas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.steps[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Steps → Default → Primary → Etapas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.steps[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Steps → Default → Primary*
 */
export interface StepsSliceDefaultPrimary {
  /**
   * Etapas field in *Steps → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  steps: prismic.GroupField<Simplify<StepsSliceDefaultPrimaryStepsItem>>;
}

/**
 * Default variation for Steps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Steps*
 */
type StepsSliceVariation = StepsSliceDefault;

/**
 * Steps Shared Slice
 *
 * - **API ID**: `steps`
 * - **Description**: Steps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSlice = prismic.SharedSlice<"steps", StepsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GrupoReflexivoDocument,
      GrupoReflexivoDocumentData,
      GrupoReflexivoDocumentDataSlicesSlice,
      GrupoReflexivoDocumentDataSlices1Slice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceMobilePrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceMobile,
      FaqSlice,
      FaqSliceDefaultPrimaryQuestionsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      StatementSlice,
      StatementSliceDefaultPrimaryStatementsItem,
      StatementSliceDefaultPrimary,
      StatementSliceVariation,
      StatementSliceDefault,
      StepsSlice,
      StepsSliceDefaultPrimaryStepsItem,
      StepsSliceDefaultPrimary,
      StepsSliceVariation,
      StepsSliceDefault,
    };
  }
}
