// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  cta: dynamic(() => import("./Cta")),
  statement: dynamic(() => import("./Statements")),
};
