// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  cta: dynamic(() => import("./Cta")),
  faq: dynamic(() => import("./Faq")),
  statement: dynamic(() => import("./Statements")),
  steps: dynamic(() => import("./Steps")),
};
